plugins {
  // https://github.com/nemerosa/versioning
  id 'net.nemerosa.versioning' version '3.1.0'
}

ext {
  testingCommonGradle = "https://raw.githubusercontent.com/interlok-testing/testing_common/refs/heads/master/common.gradle?timestamp=${new Date().getTime()}"
  //testingCommonGradle = "../interlok-testing-common/common.gradle"
  interlokTestingVersion = "0.1"
  interlokVersion = '5.0-SNAPSHOT'
  includeWar='true'
}

allprojects {
  apply from: "${testingCommonGradle}"
  // specify the version of the configuration.
  version=versioning.info.full
}

configurations.all {
  resolutionStrategy.cacheChangingModulesFor 0, "seconds"
}

dependencies {
  interlokRuntime ("com.adaptris:interlok-json:$interlokVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-webservice-cxf:$interlokVersion") { changing=true }
  
  interlokRuntime ("org.fusesource.jansi:jansi:2.0.1")

  interlokJavadocs group: "com.adaptris", name: "interlok-json", version: "$interlokVersion", classifier: "javadoc", changing: true, transitive: false
  interlokJavadocs group: "com.adaptris", name: "interlok-webservice-cxf", version: "$interlokVersion", classifier: "javadoc", changing: true, transitive: false
  
  interlokTestRuntime ("com.adaptris:interlok-service-tester:$interlokVersion") { changing=true }

  testImplementation group: "com.adaptris", name: "interlok-testing-common", version: "$interlokTestingVersion"
}
